### ISSUE TITLE
Test failure with gui

### ISSUE THREAD

**Issue by primejava** [shepnerd/inpainting_gmcnn#28]
ValueError: Cannot feed value of shape (1, 512, 512, 3) for Tensor 'Placeholder:0', which has shape '(1, 512, 680, 3)'

I used a 512*512 color picture provided by your project.

**Comment by shepnerd** [comment]
You can address this error by using the following comand:
`python painter_gmcnn.py --load_model_dir MODEL_PATH --img_shapes 512,512 --mode silent`,
where MODEL_PATH can be replaced with yours.

You mentioned error is caused by the default image size in the gui launching script, which is 512*680 for testing places2 images.

**Comment by primejava** [comment]
thanks ,it work
